### ISSUE TITLE
Bot Crashes on Start

### ISSUE THREAD

**Issue by thebeanogamer** [CyberDiscovery/cyberdisc-bot#61]
**Describe the bug**
The bot crashes when trying to launch.

**To Reproduce**
1. Try and start the bot

**Expected behavior**
The bot should start

**Screenshots**
`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/bot/__main__.py", line 41, in <module>
    bot.load_extension("bot.cogs.cyber")
  File "/usr/local/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 701, in load_extension
    lib.setup(self)
  File "/bot/cogs/cyber.py", line 209, in setup
    bot.add_cog(Cyber(bot))
  File "/bot/cogs/cyber.py", line 20, in __init__
    re.IGNORECASE)
  File "/usr/local/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/usr/local/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/local/lib/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/local/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/usr/local/lib/python3.6/sre_parse.py", line 696, in _parse
    p = _parse_sub(source, state, verbose, nested + 1)
  File "/usr/local/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/usr/local/lib/python3.6/sre_parse.py", line 765, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "/usr/local/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/usr/local/lib/python3.6/sre_parse.py", line 616, in _parse
    source.tell() - here + len(this))
sre_constants.error: nothing to repeat at position 46
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5a5b13beb8>`

**Comment by thebeanogamer** [comment]
![image](https://user-images.githubusercontent.com/3729048/48168381-df35ca80-e2e6-11e8-9969-b3d1b2a7331b.png)

**Comment by AnonGuy** [comment]
Resolved by #63
